#!/usr/bin/env bash
set -euo pipefail
command -v ai-task-gates >/dev/null 2>&1 || { printf '%s\n' 'ERROR: ai-task-gates must be on PATH' >&2; exit 1; }
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT; cd "$ROOT"; export AI_TASK_GATES_DIR="$TMP/state"; failures=0; passes=0
pass(){ passes=$((passes + 1)); printf 'PASS: %s\n' "$1"; }; fail(){ printf 'FAIL: %s\n' "$1" >&2; failures=$((failures + 1)); }
expect(){ printf '%s\n' "$1" > "$TMP/path"; actual="$(ai-task-gates explain --json --paths-from "$TMP/path" | jq -r .observed_class)"; [ "$actual" = infrastructure ] && pass "$2" || fail "$2 (got $actual)"; }
expect README.md 'orientation remains infrastructure'; expect AGENTS.md 'rulebook remains infrastructure'; expect .ai-devops/task-gates.json 'policy remains infrastructure'; expect .github/workflows/apply.yml 'apply workflow remains infrastructure'; expect roles/docker/tasks/main.yml 'Docker role remains infrastructure'; expect inventory/group_vars/all.yml 'host variables remain infrastructure'; expect docs/deployment.md 'deployment documentation remains infrastructure'; expect tests/test-task-gates.sh 'gate test remains infrastructure'
fixture="$TMP/ansible"; git -C "$TMP" init --quiet ansible; git -C "$fixture" config user.name 'Task Gate Test'; git -C "$fixture" config user.email task-gate-test@example.invalid; git -C "$fixture" remote add origin https://github.com/example/ansible-fixture.git; mkdir -p "$fixture/.ai-devops"; cp "$ROOT/.ai-devops/task-gates.json" "$fixture/.ai-devops/task-gates.json"; git -C "$fixture" add .; git -C "$fixture" commit --quiet -m baseline
( cd "$fixture"; ai-task-gates start --class code --base HEAD >/dev/null; mkdir -p roles/fixture/tasks; printf '%s\n' '---' > roles/fixture/tasks/main.yml )
blocked(){ local rc; set +e; (cd "$fixture" && ai-task-gates check --before ship "$@") >/dev/null 2>&1; rc=$?; set -e; [ "$rc" -eq 3 ]; }
blocked && pass 'infrastructure escalation refuses mismatched shipping' || fail 'infrastructure escalation did not refuse'; blocked --acknowledge fixture && pass 'acknowledgement cannot bypass infrastructure' || fail 'acknowledgement bypassed infrastructure'; blocked --owner-request fixture && pass 'owner flag cannot bypass infrastructure' || fail 'owner flag bypassed infrastructure'
( cd "$fixture"; ai-task-gates start --class infrastructure --base HEAD >/dev/null; ai-task-gates check --before ship >/dev/null ) && pass 'declared infrastructure flow reaches shipping checks' || fail 'declared infrastructure flow was refused'
set +e; (cd "$fixture" && ai-task-gates check --before infrastructure) >/dev/null 2>&1; action_rc=$?; set -e; [ "$action_rc" -eq 3 ] && pass 'infrastructure mutation remains forbidden' || fail "infrastructure mutation was not refused (exit $action_rc)"
set +e; (cd "$fixture" && ai-task-gates check --before infrastructure --acknowledge fixture) >/dev/null 2>&1; action_ack_rc=$?; set -e; [ "$action_ack_rc" -eq 3 ] && pass 'acknowledgement cannot bypass infrastructure mutation refusal' || fail "acknowledgement bypassed infrastructure mutation refusal (exit $action_ack_rc)"
set +e; (cd "$fixture" && ai-task-gates check --before infrastructure --owner-request fixture) >/dev/null 2>&1; action_owner_rc=$?; set -e; [ "$action_owner_rc" -eq 3 ] && pass 'owner flag cannot bypass infrastructure mutation refusal' || fail "owner flag bypassed infrastructure mutation refusal (exit $action_owner_rc)"
set +e; (cd "$fixture" && ai-task-gates check --before production --acknowledge fixture) >/dev/null 2>&1; prod_ack_rc=$?; set -e; [ "$prod_ack_rc" -eq 3 ] && pass 'acknowledgement cannot bypass production refusal' || fail "acknowledgement bypassed production refusal (exit $prod_ack_rc)"
set +e; (cd "$fixture" && ai-task-gates check --before production --owner-request fixture) >/dev/null 2>&1; prod_owner_rc=$?; set -e; [ "$prod_owner_rc" -eq 3 ] && pass 'owner flag cannot bypass production refusal' || fail "owner flag bypassed production refusal (exit $prod_owner_rc)"
cp "$fixture/.ai-devops/task-gates.json" "$TMP/policy"; rm "$fixture/.ai-devops/task-gates.json"; printf '%s\n' roles/fixture/tasks/main.yml > "$TMP/path"; before="$(cd "$fixture" && ai-task-gates explain --json --paths-from "$TMP/path" | jq -r .observed_class)"; cp "$TMP/policy" "$fixture/.ai-devops/task-gates.json"; after="$(cd "$fixture" && ai-task-gates explain --json --paths-from "$TMP/path" | jq -r .observed_class)"; [ "$before" = code ] && [ "$after" = infrastructure ] && cmp -s "$TMP/policy" "$fixture/.ai-devops/task-gates.json" && pass 'byte-exact rollback and restore control holds' || fail "rollback control failed ($before/$after)"
[ "$failures" -eq 0 ] || exit 1; printf '%s passed / 0 failed\n' "$passes"
