---
- name: Reconcile Windows developer computers
  hosts: windows_dev
  gather_facts: true
  roles:
    - role: dev_windows
      tags: [dev_windows]

- name: Reconcile Ubuntu developer computers
  hosts: ubuntu_dev
  become: true
  gather_facts: true
  roles:
    - role: dev_ubuntu
      tags: [dev_ubuntu]
